var menudata={children:[
{text:"Strona główna",url:"index.html"},
{text:"Struktury Danych",url:"annotated.html",children:[
{text:"Struktury danych",url:"annotated.html"}]},
{text:"Pliki",url:"files.html",children:[
{text:"Lista plików",url:"files.html"},
{text:"Globalne",url:"globals.html",children:[
{text:"Wszystko",url:"globals.html",children:[
{text:"_",url:"globals.html#index__"},
{text:"a",url:"globals.html#index_a"},
{text:"b",url:"globals.html#index_b"},
{text:"c",url:"globals.html#index_c"},
{text:"d",url:"globals.html#index_d"},
{text:"e",url:"globals.html#index_e"},
{text:"f",url:"globals.html#index_f"},
{text:"g",url:"globals.html#index_g"},
{text:"i",url:"globals.html#index_i"},
{text:"l",url:"globals.html#index_l"},
{text:"m",url:"globals.html#index_m"},
{text:"o",url:"globals.html#index_o"},
{text:"p",url:"globals.html#index_p"},
{text:"q",url:"globals.html#index_q"},
{text:"s",url:"globals.html#index_s"},
{text:"t",url:"globals.html#index_t"},
{text:"w",url:"globals.html#index_w"}]},
{text:"Funkcje",url:"globals_func.html",children:[
{text:"_",url:"globals_func.html#index__"},
{text:"a",url:"globals_func.html#index_a"},
{text:"b",url:"globals_func.html#index_b"},
{text:"c",url:"globals_func.html#index_c"},
{text:"d",url:"globals_func.html#index_d"},
{text:"f",url:"globals_func.html#index_f"},
{text:"g",url:"globals_func.html#index_g"},
{text:"i",url:"globals_func.html#index_i"},
{text:"l",url:"globals_func.html#index_l"},
{text:"m",url:"globals_func.html#index_m"},
{text:"p",url:"globals_func.html#index_p"},
{text:"q",url:"globals_func.html#index_q"},
{text:"s",url:"globals_func.html#index_s"},
{text:"t",url:"globals_func.html#index_t"},
{text:"w",url:"globals_func.html#index_w"}]},
{text:"Zmienne",url:"globals_vars.html"},
{text:"Wyliczenia",url:"globals_enum.html"}]}]}]}
